import csv
import json
import os

system_message = 'You are a teacher model that would give accurate, logical assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher_v6.jsonl')
except:
    pass

with open("origin/pairs-partial-1.json", mode='r', encoding='utf-8') as pairs:
    data = json.load(pairs)
    with open('datasets/teacher_v6.jsonl', mode='a+') as teacher:
        for d in data:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model cannot give a readable, reasonable, accurate result. As a teacher, please try to give me a better translation. Please follow the grammar rule and language convention, arrange the sentence in the right order, and use the right psychological terminology.'.format(d['en'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Of course. A better translation is "{0}"'.format(d['zh'])
                    }
                ]
            }, ensure_ascii=False) + '\n')