import csv
import json
import os

system_message = 'You are a teacher model that would give "good or bad" assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher.jsonl')
except:
    pass

with open("origin/comparison.csv", mode='r', encoding='utf-8-sig') as comparison:
    reader = csv.DictReader(comparison)
    with open('datasets/teacher.jsonl', mode='a+') as teacher:
        for row in reader:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model gives the result: "{1}". Is it good or bad?'.format(row['OriginalContent'], row['BadTranslation'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Bad'
                    }
                ]
            }, ensure_ascii=False) + '\n')
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model gives the result: "{1}". Is it good or bad?'.format(row['OriginalContent'], row['GoodTranslation'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Good'
                    }
                ]
            }, ensure_ascii=False) + '\n')