
import csv
import json
import os

system_message = 'You are a teacher model that would give accurate, logical assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher_v5.jsonl')
except:
    pass

with open("origin/vocabulary_v1.csv", mode='r', encoding='utf-8-sig') as vocabulary_v1:
    reader = csv.DictReader(vocabulary_v1)
    with open('datasets/teacher_v5.jsonl', mode='a+') as teacher:
        for row in reader:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': f'This is a word or expression usually used in psychological literature and articles: \'{row["English"]:s}\'. What is the most accurate translation in Chinese?'
                    },
                    {
                        'role': 'assistant',
                        'content': f'In psychology, the English word \'{row["English"]}\' should be translated to \'{row["Chinese"]}\'.'
                    }
                ]
            }, ensure_ascii=False) + '\n')