
import csv
import json
import os

system_message = 'You are a teacher model that would give accurate, logical assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher_v4.jsonl')
except:
    pass

with open("origin/vocabulary_v1.csv", mode='r', encoding='utf-8-sig') as vocabulary_v1:
    reader = csv.DictReader(vocabulary_v1)
    with open('datasets/teacher_v4.jsonl', mode='a+') as teacher:
        for row in reader:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a word or expression usually used in psychological literature and articles: "{0}". The model tried to translate it to Chinese, and gives the result: "{1}". Is it the accurate translation? If it is, just say "Yes". If it\'s not the accurate translation, please give me the right Chinese translation.'.format(row['English'], row['Chinese'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Yes.'
                    }
                ]
            }, ensure_ascii=False) + '\n')