import csv
import json
import os

system_message = 'You are a teacher model that would give accurate, logical assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher_v3.jsonl')
except:
    pass

with open("origin/pairs.json", mode='r', encoding='utf-8') as pairs:
    data = json.load(pairs)
    with open('datasets/teacher_v3.jsonl', mode='a+') as teacher:
        for d in data:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model gives the result: "{1}". Is it good or bad? If it\'s bad, please give me the good translation, and if it\'s good, please say GOOD.'.format(d['en'], d['zh'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Good.'
                    }
                ]
            }, ensure_ascii=False) + '\n')