import csv
import json
import os

system_message = 'You are a teacher model that would give accurate, logical assessment on translation generated by other model.'

try:
    os.remove('datasets/teacher_v2.jsonl')
except:
    pass

with open("origin/comparison_v1.csv", mode='r', encoding='utf-8-sig') as comparison:
    reader = csv.DictReader(comparison)
    with open('datasets/teacher_v2.jsonl', mode='a+') as teacher:
        for row in reader:
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model gives the result: "{1}". Is it good or bad? If it\'s bad, please give me the good translation, and if it\'s good, please say GOOD.'.format(row['OriginalContent'], row['BadTranslation'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Bad. A better translation is "{0}".'.format(row['GoodTranslation'])
                    }
                ]
            }, ensure_ascii=False) + '\n')
            teacher.writelines(json.dumps({
                'messages': [
                    {
                        'role': 'system',
                        'content': system_message
                    },
                    {
                        'role': 'user',
                        'content': 'This is a paragraph in English that needs to be translated: "{0}". The model gives the result: "{1}". Is it good or bad? If it\'s bad, please give me the good translation, and if it\'s good, please say GOOD.'.format(row['OriginalContent'], row['GoodTranslation'])
                    },
                    {
                        'role': 'assistant',
                        'content': 'Good.'
                    }
                ]
            }, ensure_ascii=False) + '\n')
